@Library('shared-library') _

ci_pipeline(
    awsRegion: 'us-east-1',
    ecrUrl: '006262944085.dkr.ecr.us-east-1.amazonaws.com',
    imageName: 'yasmin-checkpoint-home-exam-consumer-ecr',
    cdJob: 'CD',
    infraImageVerProperty: 'consumer_image_tag'
)