pipeline {
    agent any
    options {
        timestamps()

        timeout(time:60, unit:'MINUTES')

    }

    parameters {
        string(name: 'key_to_change', description: 'The key to modify during deployment')
        string(name: 'value', description: 'The new value for the key')
    }

    stages {
        stage ("test") {
            steps {
                script {
                    echo "hi!"
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}

