pipeline {
    agent any
    options {
        timestamps()

        timeout(time:60, unit:'MINUTES')

    }

    parameters {
        string(name: 'key_to_change', description: 'The key to modify during deployment')
        string(name: 'value', description: 'The new value for the key')
    }

    stages {
        // stage('Checkout Code') {
        //     steps {
        //         // This will use the SCM configuration from the Jenkins UI
        //         checkout scm
        //     }
        // }
        stage ("test") {
            steps {
                script {
                    echo "hi!"
                    echo "${key_to_change}"
                    echo "${value}"
                    sh "ls"
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}

