pipeline {
    agent any
    options {
        timestamps()

        timeout(time:15, unit:'MINUTES')

        buildDiscarder(logRotator(
            numToKeepStr: '4',
            daysToKeepStr: '7',
            artifactNumToKeepStr:'30'
        ))
    }
    environment {
        AWS_REGION = 'us-east-1'
        ECR_URL = '006262944085.dkr.ecr.us-east-1.amazonaws.com'
        IMAGE_NAME = 'yasmin-checkpoint-home-exam-rest-ecr'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }
        stage('Tag') {
            steps {
                script {
                    def latestTag = sh(script: "docker pull ${ECR_URL}:latest || true", returnStdout: true).trim()
                    
                    if (latestTag) {
                        latestTag = sh(script: "docker images --format '{{.Tag}}' <repository> | head -n 1", returnStdout: true).trim()
                        
                        def parts = latestTag.tokenize('.')
                        def lastDigit = (parts[-1] as int) + 1
                        latestTag = "${parts[0]}.${parts[1]}.${lastDigit}"
                    } else {
                        latestTag = "1.0.0"
                    }

                    echo "Next version tag: ${latestTag}"
                    sh "docker tag ${IMAGE_NAME}:latest ${ECR_URL}/${IMAGE_NAME}:${latestTag}"
                }
            }
        }
        stage('Publish') {
            steps {
                script {
                    sh "docker push ${env.ECR_URL}/${env.IMAGE_NAME}:${latestTag}"
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Hey'
            }
        }
    }
    post {
        always {
            sh 'docker image prune -f'
            deleteDir()
        }
    }
}

